[package]
name = "kaonic"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
reticulum = { path = "../../reticulum-rs" }
log = "0.4.26"
android_log = "0.1.3"

# Async IO
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.14"

[lib]
crate-type = ["staticlib", "dylib"]
